### ISSUE TITLE
[Bug] Registering seems to be broken

### ISSUE THREAD

**Issue by DylanHobbs** [TrapScan/TrapScan_Test#40]
Tried to create an account but got a 500.

I was using the "+1" cheat for email.

Steps to reproduce:
Go to app home page
Login with email 
Register account
Email: dylan+1@domain.ie
500 error

![image](https://user-images.githubusercontent.com/8566772/191672963-34f40751-5c2a-4cda-a495-ce7b278fe97a.png)

**Comment by KurtisPapple** [comment]
I get the same 
![image](https://user-images.githubusercontent.com/80499565/191896279-ce9e0677-9fa1-46a6-8489-941c9101848a.png)
